name: Compile and test
on:
  workflow_call:
    inputs:
      rice-config:
        required: false
        type: string
        default: 'github:emacs-twist/rice-config'
      melpa:
        required: false
        type: string
        default: 'github:melpa/melpa'
      systems:
        required: false
        type: string
        default: 'github:nix-systems/default'
      registries:
        required: false
        type: string
        default: 'github:emacs-twist/registries'
      lock-dir:
        required: false
        type: string
        default: '.rice-lock/default'
jobs:
  matrix:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.matrix.outputs.matrix }}
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7
        with:
          persist-credentials: false
      - uses: nixbuild/nix-quick-install-action@9f63be77f412a248c9d9a65a4c82cf066cdf8f0c # v35
      - name: Get the matrix
        id: matrix
        env:
          LOCK_DIR: ${{ inputs.lock-dir }}
          MELPA: ${{ inputs.melpa }}
          REGISTRIES: ${{ inputs.registries }}
          RICE_CONFIG: ${{ inputs.rice-config }}
          SYSTEMS: ${{ inputs.systems }}
        run: |
          set -e
          nix_args=(
            --override-input rice-src "path:$PWD"
            --override-input melpa "$MELPA"
            --override-input registries "$REGISTRIES"
            --override-input systems "$SYSTEMS"
          )
          if [[ -n "$LOCK_DIR" ]]; then
            nix_args+=(--override-input rice-lock "path:$PWD/$LOCK_DIR")
          fi
          echo "matrix=$(nix eval "${RICE_CONFIG}#github.matrix" "${nix_args[@]}" --json)" \
            >> "$GITHUB_OUTPUT"
  build:
    needs: matrix
    strategy:
      matrix: ${{ fromJSON(needs.matrix.outputs.matrix) }}
      fail-fast: false
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7
        with:
          persist-credentials: false
      - uses: nixbuild/nix-quick-install-action@9f63be77f412a248c9d9a65a4c82cf066cdf8f0c # v35
      - name: Byte compile
        env:
          ARCH: ${{ matrix.arch }}
          EMACS: ${{ matrix.emacs }}
          LOCK_DIR: ${{ inputs.lock-dir }}
          MELPA: ${{ inputs.melpa }}
          REGISTRIES: ${{ inputs.registries }}
          RICE_CONFIG: ${{ inputs.rice-config }}
          SYSTEMS: ${{ inputs.systems }}
          TARGET: ${{ matrix.target }}
        run: |
          nix_args=(
            --override-input rice-src "path:$PWD"
            --override-input melpa "$MELPA"
            --override-input registries "$REGISTRIES"
            --override-input systems "$SYSTEMS"
          )
          if [[ -n "$LOCK_DIR" ]]; then
            nix_args+=(--override-input rice-lock "path:$PWD/$LOCK_DIR")
          fi
          nix build \
            "${RICE_CONFIG}#checks.${ARCH}.${TARGET}-compile-${EMACS}" \
            "${nix_args[@]}" \
            --print-build-logs
      # The same options as byte-compile except for the subcommand (test-type)
      # and the installable (test-derivation).
      - name: Test
        if: ${{ matrix.test-type }}
        env:
          LOCK_DIR: ${{ inputs.lock-dir }}
          MELPA: ${{ inputs.melpa }}
          REGISTRIES: ${{ inputs.registries }}
          RICE_CONFIG: ${{ inputs.rice-config }}
          SYSTEMS: ${{ inputs.systems }}
          TEST_DERIVATION: ${{ matrix.test-derivation }}
          TEST_TYPE: ${{ matrix.test-type }}
        run: |
          nix_args=(
            --override-input rice-src "path:$PWD"
            --override-input melpa "$MELPA"
            --override-input registries "$REGISTRIES"
            --override-input systems "$SYSTEMS"
          )
          if [[ -n "$LOCK_DIR" ]]; then
            nix_args+=(--override-input rice-lock "path:$PWD/$LOCK_DIR")
          fi
          nix "$TEST_TYPE" \
            "${RICE_CONFIG}#${TEST_DERIVATION}" \
            "${nix_args[@]}" \
            --print-build-logs
